# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 21:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_auto_20170826_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('due_date', models.DateTimeField(verbose_name='Fecha Limite')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Publicacion')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Actualizada')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregunta_create_user', to=settings.AUTH_USER_MODEL)),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregunta_update_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaValidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Publicacion')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizada')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respusta_valida_create_user', to=settings.AUTH_USER_MODEL)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Pregunta')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respusta_valida_update_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='preguntas',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='preguntas',
            name='update_user',
        ),
        migrations.AlterUniqueTogether(
            name='respuestasvalidas',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='respuestasvalidas',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='respuestasvalidas',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='respuestasvalidas',
            name='update_user',
        ),
        migrations.AlterField(
            model_name='apuestas',
            name='pregunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Pregunta'),
        ),
        migrations.AlterField(
            model_name='apuestas',
            name='respuesta_valida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.RespuestaValidas'),
        ),
        migrations.DeleteModel(
            name='Preguntas',
        ),
        migrations.DeleteModel(
            name='RespuestasValidas',
        ),
        migrations.AlterUniqueTogether(
            name='respuestavalidas',
            unique_together=set([('pregunta', 'text')]),
        ),
    ]
